### ISSUE TITLE
Scheduling based on effective sample size

### ISSUE THREAD

**Issue by urbainvaes** [PdIPS/CBXpy#15]
Hi Tim,

Thanks for all your work on this!

I'm in the process of implementing CBS in the Julia package, and I try to (loosely) follow the structure of your code. I was wondering whether you had implemented a scheduler based on effective sample size? And if not, is this something that you think would be easily doable with the current way that scheduling works?

In an old code, I was doing this with a (pretty messily implemented) bisection method as follows:
```julia
function find_beta(fensembles, ess)
    fensembles = fensembles .- minimum(fensembles)
    J = length(fensembles)
    function get_ess(β)
        weights = exp.(- β*fensembles)
        return sum(weights)^2/sum(weights.^2)/J
    end
    β1, β2 = 0, 1e20
    β, e = β2, get_ess(β2)
    if e > ess
        println("Can't find β")
        return β
    end
    while abs(e - ess) > 1e-2
        β = (β1 + β2)/2
        e = get_ess(β)
        if e > ess
            β1 = β
        else
            β2 = β
        end
    end
    return β
end
```

Best wishes,

Urbain

**Comment by TimRoith** [comment]
Hi Urbain,

I just added an implementation based on your suggestion in the file scheduler.py

It is still untested, so there might still be bugs, but the basic structure should work. A usage example can be found in the Notebook simple_example.py

Best
Tim

**Comment by TimRoith** [comment]
I think with the adjustments according to this comment here https://github.com/PdIPS/CBXpy/commit/6250072891b33978594f4f88d97eac1d2853825c#r139200160 the scheduler now works. There is one basic unit test, maybe we can think of another one, but for now I would close this issue. Feel free to reopen it.

Best
Tim
