### ISSUE TITLE
[JOSS] Missing contributing guidelines

### ISSUE THREAD

**Issue by AlessandroPierro** [PdIPS/CBXpy#23]
Hi, CBXpy team!

The repository needs contribution guidelines for the community. This is required for acceptance based on the JOSS review checklist: "_Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support_".

I would encourage you to have a look at [GitHub - Setting guidelines for repository contributors](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) for some ideas.

**Comment by TimRoith** [comment]
Hi,

thanks a lot for pointing this out, and sorry for missing including the guidelines. I just added the CONTRIBUTING.md [here](https://github.com/PdIPS/CBXpy/blob/main/CONTRIBUTING.md) and hope that it gives a good overview of how to contribute.

Let me know if you think it's fine, and thanks again.
Best
Tim

**Comment by AlessandroPierro** [comment]
Looks good, thank you for your quick answer!
