### ISSUE TITLE
JOSS Review Comments

### ISSUE THREAD

**Issue by Bobby-Huggins** [PdIPS/CBXpy#28]
Hi @rafaelbailo et al., thank you for the submission. Overall I found the paper very clear and well-written, and the package very well-documented and easy to use.

# Python Package

1. I might have missed it, but it looks like the `pytest` cases for the most part don't test the optimum/optimizer for known objectives (e.g. that `Rosenbrock()` has a minimum of 1.0 at (1.0, 1.0)). I only see that the minimum of the `Quadratic` objective is confirmed to be near zero, I recommend adding tests for some more complex cases.
2. In running the [plotting example](https://pdips.github.io/CBXpy/userguide/plotting.html), I receive a `TypeError: Shapes of x (50, 50) and z (100, 50) do not match` when calling `plotter.init_plot()`: it looks like `cbx` is trying to make a contour plot, even though the objective is 1-D. I receive a different but related error if the objective is 3-D, but it works if the objective is 2-D. If you're able to replicate then it's worth checking how the plotting functionality handles dimensions (and maybe adding test cases).
3. This is minor (a matter of taste and not necessary for the JOSS submission) but perhaps consider following a `CamelCase` convention for the plotting class, rather than `snake_case`.
4. This is *very* minor: there's an extra backslash [here](https://github.com/PdIPS/CBXpy/blob/05d1530cf2a2ba2bb974edaea1d36298e9112b97/docs/userguide/dynamics.rst?plain=1#L28) ``\:math:`mathcal{X}` `` causing the math to not render properly.

# Paper

1. In the statement of need, you cite Kim and Choi's package `BayesO`, but there are many existing Bayesian optimization libraries: I would recommend either dropping the citation (since it's not so relevant to particle-based methods) or citing the other significant existing libraries alongside it.
2. This is minor, and covered already by another reviewer, but I think it would be natural to name the existing packages in the statement of need (not just their authors).

**Comment by TimRoith** [comment]
Thank you very much for the review. I will address the points you raised below:

Ad 1) In the recent commit, I added a unit test, that checks the performance for Ackley, Rastrigin and three-hump camel:

https://github.com/PdIPS/CBXpy/blob/7605a73213cbab6d8b206a87c668bb721238d58f/tests/dynamics/test_abstraction.py#L31C1-L40C69

**Comment by TimRoith** [comment]
Ad 2) Thanks for spotting this. I fixed the 1D case, it should work now. I am still trying to replicate the 3D error. Could you maybe provide a snippet creating this error?

**Comment by TimRoith** [comment]
Ad 3) I changed the classes in plotting to camel case.

Ad 4) Thanks for spotting this. I fixed the mistake.

**Comment by TimRoith** [comment]
Concerning the comments on the paper:

Ad 1) We now try to cite more relevant packages for Bayesian Optimization, namely: `BayesO`, `bayesian-optimization`, `GPyOpt`, `GPflowOpt`, `pyGPGO` and `BoTorch`. We hope we didn't miss an important one, but please feel free to suggest other relevant packages.

Ad 2) Indeed, we type out the names now and it reads much better.

**Comment by Bobby-Huggins** [comment]
Hi @TimRoith, thanks for the quick response and changes!

Regarding 2), if you're testing dimensions 1-4 and it works then tracking down this error is probably not necessary for the JOSS submission. But in any case here is a snippet to reproduce the error (with Python 3.11.7 and up-to-date `main` branch):
```python
from cbx.dynamics import CBXDynamic
from cbx.plotting import PlotDynamic
dyn = CBXDynamic(lambda x: x[0]**2 + x[1]**2 + x[2]**2, d=3)
plotter = PlotDynamic(dyn)
plotter.init_plot()
```
for which I get the following error:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bug/CBXpy/cbx/plotting.py", line 117, in init_plot
    self.plot_objective()
  File "/home/bug/CBXpy/cbx/plotting.py", line 146, in plot_objective
    _ = contour_2D(self.dyn.f, ax=self.ax, **self.objective_args)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bug/CBXpy/cbx/plotting.py", line 30, in contour_2D
    Z = f(Z)
        ^^^^
  File "/home/bug/CBXpy/cbx/utils/objective_handling.py", line 37, in __call__
    return self.apply(x)
           ^^^^^^^^^^^^^
  File "/home/bug/CBXpy/cbx/utils/objective_handling.py", line 77, in apply
    return np.apply_along_axis(self.f, 1, x.reshape(-1, x.shape[-1])).reshape(-1,x.shape[-2])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/zpsds7bi7skvmlv1lnln46k7m2q649ww-python3.11-numpy-1.26.2/lib/python3.11/site-packages/numpy/lib/shape_base.py", line 379, in apply_along_axis
    res = asanyarray(func1d(inarr_view[ind0], *args, **kwargs))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<stdin>", line 1, in <lambda>
IndexError: index 2 is out of bounds for axis 0 with size 2
```

**Comment by Bobby-Huggins** [comment]
Regarding Python packages for Bayesian optimization, I might (somewhat selfish) plug for PyBADS ([JOSS paper](https://joss.theoj.org/papers/10.21105/joss.05694), [GitHub](https://github.com/acerbilab/pybads)): I was not directly involved with the package but my PI at Helsinki was. However, I leave it to your discretion whether to include it.

**Comment by TimRoith** [comment]
> Regarding Python packages for Bayesian optimization, I might (somewhat selfish) plug for PyBADS ([JOSS paper](https://joss.theoj.org/papers/10.21105/joss.05694), [GitHub](https://github.com/acerbilab/pybads)): I was not directly involved with the package but my PI at Helsinki was. However, I leave it to your discretion whether to include it.

Sorry for missing this, it is of course cited now, in the newest version of the paper.

**Comment by TimRoith** [comment]
> Hi @TimRoith, thanks for the quick response and changes!
> 
> Regarding 2), if you're testing dimensions 1-4 and it works then tracking down this error is probably not necessary for the JOSS submission. But in any case here is a snippet to reproduce the error (with Python 3.11.7 and up-to-date `main` branch):
> 
> ```python
> from cbx.dynamics import CBXDynamic
> from cbx.plotting import PlotDynamic
> dyn = CBXDynamic(lambda x: x[0]**2 + x[1]**2 + x[2]**2, d=3)
> plotter = PlotDynamic(dyn)
> plotter.init_plot()
> ```
> 
> for which I get the following error:
> 
> ```python
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/bug/CBXpy/cbx/plotting.py", line 117, in init_plot
>     self.plot_objective()
>   File "/home/bug/CBXpy/cbx/plotting.py", line 146, in plot_objective
>     _ = contour_2D(self.dyn.f, ax=self.ax, **self.objective_args)
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/bug/CBXpy/cbx/plotting.py", line 30, in contour_2D
>     Z = f(Z)
>         ^^^^
>   File "/home/bug/CBXpy/cbx/utils/objective_handling.py", line 37, in __call__
>     return self.apply(x)
>            ^^^^^^^^^^^^^
>   File "/home/bug/CBXpy/cbx/utils/objective_handling.py", line 77, in apply
>     return np.apply_along_axis(self.f, 1, x.reshape(-1, x.shape[-1])).reshape(-1,x.shape[-2])
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/nix/store/zpsds7bi7skvmlv1lnln46k7m2q649ww-python3.11-numpy-1.26.2/lib/python3.11/site-packages/numpy/lib/shape_base.py", line 379, in apply_along_axis
>     res = asanyarray(func1d(inarr_view[ind0], *args, **kwargs))
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<stdin>", line 1, in <lambda>
> IndexError: index 2 is out of bounds for axis 0 with size 2
> ```

Thank you very much for the snippet. The choice of loss function was not caught in my test. I fixed the bug that caused this and updated the tests using the function definition you provided. Your example also works now.

**Comment by Bobby-Huggins** [comment]
Thanks, @TimRoith! Closing as completed.
